version: '3'

services:
  app:
    build:
      context: .
      dockerfile: compose/svc.Dockerfile
    image: nxsearch-svc
    depends_on:
      - lib
    ulimits:
      nofile:
        soft: 65536
        hard: 1048576
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/data

  lib:
    build:
      context: .
      dockerfile: compose/nxsearch.Dockerfile
    image: nxsearch
    volumes:
      - ./data:/data
      - ./src:/src
