version: '3'

services:
  app:
    build:
      context: .
      dockerfile: compose/svc.Dockerfile
      target: nxsearch-svc
    image: nxsearch-svc
    ulimits:
      nofile:
        soft: 65536
        hard: 1048576
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/nxsearch/data
      # DEV-only:
      #- ./svc-src/nxsearch_svc.lua:/usr/local/openresty/lualib/nxsearch_svc.lua
      #- ./svc-src/nxsearch_storage.lua:/usr/local/openresty/lualib/nxsearch_storage.lua
      # - ./compose/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      # - ./compose/openapi.json:/app/public_html/openapi.json
  lib:
    build:
      context: .
      dockerfile: compose/svc.Dockerfile
      target: nxsearch
    image: nxsearch
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./data:/nxsearch/data
      - ./src:/src
