name: Publish to Registry
on:
  release:
      types: [published]

env:
  RELEASE_VERSION: ${{github.event.release.name}}
  BASE_IMAGE_NAME: rmind/nxsearch-svc
  RELEASE_IMAGE_NAME: ${BASE_IMAGE_NAME}:${RELEASE_VERSION}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build
        shell: bash
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker pull ${BASE_IMAGE_NAME}:ci || echo "Can't download"
          docker buildx build \
            --tag ${RELEASE_IMAGE_NAME} \
            --cache-from ${BASE_IMAGE_NAME}:ci \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --target nxsearch-svc \
            --output type=docker \
            -f compose/svc.Dockerfile .

      - name: push
        shell: bash
        run: docker push ${RELEASE_IMAGE_NAME}
