name: Tests
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build_and_tests_linux:
    name: Build and run the tests (Linux)
    runs-on: ubuntu-24.04  # NOTE: bump in publish-pypi.yaml too
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build the image and run the tests
        # Note: runs the unit tests and Lua tests.
        uses: docker/build-push-action@v7
        with:
          context: .
          file: compose/svc.Dockerfile
          target: nxsearch-svc
          tags: rmind/nxsearch-svc:ci
          load: true  # load the image into the runner's local Docker
          cache-from: type=gha,scope=nxsearch-svc
          cache-to: type=gha,mode=max,scope=nxsearch-svc

      - name: Run the integration test
        run: |
          docker run -d \
            --name test-svc \
            -p "127.0.0.1:8000:8000" \
            rmind/nxsearch-svc:ci
          ./tools/svc_test.sh
          docker rm -f test-svc

      - name: Build the Python package
        uses: docker/build-push-action@v7
        with:
          context: .
          file: compose/pynxsearch.Dockerfile
          tags: rmind/pynxsearch:ci
          load: true
          cache-from: type=gha,scope=pynxsearch
          cache-to: type=gha,mode=max,scope=pynxsearch

      - name: Run the Python tests
        run: |
          docker run --rm rmind/pynxsearch:ci \
              uv run pytest --color=yes -ra tests

  build_and_tests_macos:
    name: Build and run the tests (MacOS)
    runs-on: macos-15  # NOTE: bump in publish-pypi.yaml too
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Install dependencies
        id: deps-macos
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-name: wheel-deps
          create-args: >-
            -c conda-forge
            icu
          init-shell: none  # don't activate the env
          cache-environment: true
          post-cleanup: none

      - name: Build-test
        env:
          DEPS_PREFIX: ${{ steps.deps-macos.outputs.environment-path }}
        run: |
          set -x
          brew install libtool cmake snowball re2c lemon
          export PKG_CONFIG_PATH="${DEPS_PREFIX}/lib/pkgconfig"

          cd src
          make distclean
          USE_LUA=0 make -j $(getconf _NPROCESSORS_ONLN) lib
